require( 'sinatra' )
require( 'sinatra/contrib/all' )
require( 'pry' )
require_relative( '../models/gym_class.rb' )
require_relative( '../models/member.rb' )
require_relative( '../models/booking.rb' )
also_reload( '../models/*' )
